-- Switch role to useradmin
USE ROLE USERADMIN;

-- Create a role for endusers
CREATE ROLE DA COMMENT = 'DATA ANALYST';

GRANT ROLE DA TO USER <own-snowflake-username>; -- Given myself the role for testing.

SHOW USERS;

-- Create an user who will actually use git repo on snowflake platform
CREATE USER <username>
    PASSWORD=<password>
    LOGIN_NAME=<user-login-name>
    EMAIL=<user-email>
    MUST_CHANGE_PASSWORD=TRUE;

USE DATABASE SNOWGIT;
-- Give all required permission to the role.
GRANT USAGE ON DATABASE SNOWGIT TO ROLE DA;

GRANT READ,WRITE ON GIT REPOSITORY PRACTICEREPO TO ROLE DA;
GRANT USAGE ON DATABASE SNOWGIT TO ROLE DA;
GRANT USAGE ON SCHEMA SNOWGIT.PUBLIC TO ROLE DA;
GRANT USAGE ON SECRET GIT_SECRET TO ROLE DA;

SHOW API INTEGRATIONS;
GRANT USAGE ON INTEGRATION GIT_API_INTEGRATION TO ROLE DA;

GRANT USAGE ON DATABASE ECOM TO ROLE DA;
GRANT USAGE ON SCHEMA ECOM.PUBLIC TO ROLE DA;


USE DATABASE ECOM;
GRANT CREATE TABLE ON SCHEMA ECOM.PUBLIC TO ROLE DA;
GRANT CREATE VIEW ON SCHEMA ECOM.PUBLIC TO ROLE DA;
GRANT CREATE STAGE ON SCHEMA ECOM.PUBLIC TO ROLE DA;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA ECOM.PUBLIC
TO ROLE DA;

GRANT SELECT, INSERT, UPDATE, DELETE
ON FUTURE TABLES IN SCHEMA ECOM.PUBLIC
TO ROLE DA;

-- Assign the user to DA role.
GRANT ROLE DA TO USER <own-snowflake-username>; 
